version: '3'

services:
  afisha-bot:
    #image: 'sintaksis1331/afisha-bot:latest'
    build:
      context: .
    container_name: afisha-bot
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/afisha
      - SPRING_DATASOURCE_USERNAME=afisha-bot
      - SPRING_DATASOURCE_PASSWORD=afisha-bot
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - AFISHA_BOT_TOKEN=6253675703:AAE_x0aNfPnnZGo5rZ7nPxSLZ58Rwxy30co
      - AFISHA_BOT_NAME=AfishaBot
      - AFISHA_BOT_ADMIN_TOKEN=6253818777:AAF8n_ns89FJOwGLvNrx0cmzk_PKtq6IkF4
      - AFISHA_BOT_ADMIN_NAME=AfishaBotAdmin
      - AFISHA_BOT_ADMIN_LOGIN=login
      - AFISHA_BOT_ADMIN_PASSWORD=password

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=afisha-bot
      - POSTGRES_PASSWORD=afisha-bot
      - POSTGRES_DB=afisha
